### PR TITLE
add wrappers to enable/disable Padding for encryption contexts

### PR DESCRIPTION
**Pull request by rameshrv**
We needed to disable and use customized padding in our product. This code change enables us (and others who need it) to have custom padding.

### CODE REVIEW

**Comment by hasit** [comment]
I need this as well. We need to turn off the default padding and do it our way because we need to comply with our clients.

**Comment by zeebo** [comment]
Thanks for this contribution. I have some changes I'd like to request in order to get it merged:

- Can you change the method to be `SetPadding(bool)` rather than two methods?
- We can't add methods to an exported interface due to back-compat concerns. Your local code can still type assert to get access to the new method.

Let me know if you're willing to make these changes. Be sure to add yourself to the AUTHORS file as well. Thanks!

**Comment by hasit** [comment]
@zeebo, can you please expand on what you meant here?

> We can't add methods to an exported interface due to back-compat concerns. Your local code can still type assert to get access to the new method.

**Comment by zeebo** [comment]
A package depending on this package may have a local implementation of the interface on some type and adding methods to it would cause that package to no longer compile because the local implementation would not have that method.

**Comment by rameshrv** [comment]
@zeebo , thank you for the reference ! It works like a charm..I have never used an exported method in that way !

I have now changed the AUTHORS file, as well as squashed my previous commits into one single commit. Do you think the current changes are good enough to merge into the main line ?

**Comment by zeebo** [comment]
Perfecf! Thanks for the work.

**Pull request merged**
